SELECT *
FROM CUSTOMERS

INSERT INTO CUSTOMERS
(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER)
VALUES
('MUSTAFA KARA', 'ÝZMÝR', '1984-09-08','KARÞIYAKA','E')

INSERT INTO CUSTOMERS
(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER)
VALUES
('MEHMET ÖZAL', 'ANTALYA', '1990-12-21', 'ALANYA', 'E')

DELETE FROM CUSTOMERS
WHERE ID NOT IN (
    SELECT TOP 1005 ID FROM CUSTOMERS ORDER BY ID
);
-- müþterilerin mevcut yaþýný hesaplama
UPDATE CUSTOMERS 
SET NATION = 'TR', AGE = DATEDIFF (YEAR, BIRTHDATE, GETDATE())

-- WHERE KOMUTU ÝLE ÝSTEDÝÐÝMÝZ ÞARTLARI SAÐLAYAN VERÝLERÝ ÇAÐIRIRIZ
SELECT * FROM CUSTOMERS  
WHERE CITY = 'ÝZMÝR'

--Ýstanbulda yaþamayanlar
SELECT * FROM CUSTOMERS
WHERE CITY <> 'ÝSTANBUL'

SELECT * FROM CUSTOMERS
WHERE GENDER ='K'
-- belirli yýl aralýðýnda doðanlar
SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'

--30 ile 45 yaþ aralýðýndakiler
SELECT * FROM CUSTOMERS
WHERE AGE BETWEEN 30 AND 45

-- ALÝ ile baþlayanlar 
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'ALÝ%'

--herhangi bir yerinde alan geçenler
select * from CUSTOMERS
where CUSTOMERNAME like '%ALan%'

select * from CUSTOMERS
where CUSTOMERNAME not like 'ali%'

-- bir veri setinde karþýlaþtýrma yapmak için "in" kullanýrýz.

select * from CUSTOMERS
where CITY in ('ÝSTANBUL', 'ANKARA')

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND DISTRICT = 'BEYLÝKDÜZÜ'

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='E' 
AND DISTRICT ='ESENLER'

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='E' 
AND BIRTHDATE BETWEEN '19900101' AND '20000101'

SELECT * FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' OR CITY ='ÝZMÝR'

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE'%LTD%'

--DISTINCT KOMUTU TEKRAR EDEN SATIRLARI TEKÝLLEÞTÝRÝR.

SELECT DISTINCT CITY FROM CUSTOMERS

SELECT DISTINCT GENDER FROM CUSTOMERS

SELECT DISTINCT AGE FROM CUSTOMERS

-- ORDER BY SIRALAMA YAPAR 

SELECT * FROM CUSTOMERS

ORDER BY ID DESC -- BÜYÜKTEN KÜÇÜÐE SIRALANIR

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%alaN%'
ORDER BY CUSTOMERNAME DESC

SELECT * FROM CUSTOMERS
ORDER BY AGE ASC -- ASC YAZMASAK DA OLUR VARSAYILANI ZATEN BU.

SELECT * FROM CUSTOMERS
ORDER BY CITY, CUSTOMERNAME

SELECT * FROM CUSTOMERS
WHERE CITY ='ÝSTANBUL'
ORDER BY AGE -- AGE YERÝNE 8 YAZILABÝLÝR

-- TOP KOMUTU VERÝLERÝN BÝR KISMINI GÖRMEMÝZÝ SAÐLAR

SELECT 
TOP 100 
* FROM CUSTOMERS -- ilk 100 kiþiyi getirir.

SELECT 
TOP 1 percent
* FROM CUSTOMERS

order by AGE -- küçükten büyük yaþý sýralar ve sadece %1'ini getirir.

-- bölüm sonu


